# how to create a null values

- None
- np.num

In [2]:
import numpy as np
import pandas as pd

# none

In [2]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
   'Age':[None,22,23,25],
   'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  23.0  Pune
3  Mahesh  25.0   NaN

In [3]:
df1.to_csv('data1.csv',index=False)

# np.nan

In [6]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
   'Age':[np.nan,22,24,25],
  'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [7]:
df2.to_csv('data2.csv',index=False)

- categorical data use **None**
- numerical data use **np.nan**

In [11]:
#for example Numerical data
np.nan+10

nan

In [10]:
None+10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [19]:
df1.isnull()
# isnull= wherever Null value there it display as True

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [20]:
df1.isnull().sum()
#counting the num of null values is there in columns

Names    1
Age      1
City     1
dtype: int64

In [21]:
df1
df1.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [nan, 23.0, 'Pune'],
       ['Mahesh', 25.0, nan]], dtype=object)

In [22]:
df1.dtypes

Names        str
Age      float64
City         str
dtype: object

In [18]:
df1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

# fill the values

In [26]:
# random fill
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  23.0  Pune
3  Mahesh  25.0    30

In [13]:
#select one column and will with  values
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: str

In [31]:
#
df1.fillna(30)
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: str

In [11]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  23.0  Pune
3  Mahesh  25.0   NaN

In [15]:
#pad,ffill,bfill,backfill
#axis=0 axis=1
df1.ffill()

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  23.0  Pune
3  Mahesh  25.0  Pune

In [17]:
df1.bfill()

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  23.0  Pune
3  Mahesh  25.0   NaN

In [22]:
df1.backfill()

AttributeError: 'DataFrame' object has no attribute 'backfill'

# mean,mediam,mode

- mean

- median

- mode

In [10]:
age_mean=df1['Age'].mean()
df1['Age'],fillna(age_mean)

NameError: name 'fillna' is not defined

In [ ]:
# there ia no particular Rule  how to fill the missing values
# it is completely  based on situation

In [25]:
Gender={'Male','Female',None}
d1=pd.DataFrame(Gender,columns=['Gender'])
d1

   Gender
0     NaN
1    Male
2  Female

In [ ]:
d={'Female':0,'Male':1}
d1

In [26]:
#the student think  that i want  to fill a missing
#data is numerical:meam
(1+0)/2

0.5

In [ ]:
Gender={'Male','Female',None}
d1=pd.DataFrame(Gender,columns=['Gender'])
d={'Female':0,'Male':1}

# situation-2

In [28]:
# Ml algorithm
# churn: stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

# situation-3

In [29]:
# no of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

# situation-4

In [32]:
course=['Ds','Ai','Ds','devops','Ai']
fee=[30000,2700,3000,22000,3000]
pd.DataFrame(zip(course,fee),columns=['course','Fees'])

   course   Fees
0      Ds  30000
1      Ai   2700
2      Ds   3000
3  devops  22000
4      Ai   3000

# KKN (k- nearest neighbours)

- KNN: K-Nearest neighbours
- where K is Number
- instead of taking avg of all the values data
     - first we will find the neighbours who are close with missing data
     - by using Euclidian distance calculation will identify the neighbour rows first
     - suppose k=2 will identify the 2 closest point first
     - those closest rows values will take it, will calculate the mean
     - Finally will fill with the mean

In [34]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
                columns=['Salary','age'])
df

    Salary  age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn
    - impute
        - KKNImputer

In [37]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)

df_new = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

df_new

    Salary   age
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0